# نام ورک‌فلو که در تب Actions گیت‌هاب نمایش داده می‌شود
name: Generate Shadowsocks Configs

# تریگرها: چه زمانی این ورک‌فلو اجرا شود
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

# تعریف جاب‌ها (مراحل اجرایی)
jobs:
  build:
    # ------------------ این بخش را اضافه کنید ------------------
    permissions:
      contents: write # به جاب اجازه می‌دهد تا محتوای ریپازیتوری را تغییر دهد (کامیت کند)
    # -----------------------------------------------------------

    # استفاده از آخرین نسخه اوبونتو برای اجرا
    runs-on: ubuntu-latest

    steps:
      # مرحله 1: دریافت کد از ریپازیتوری شما
      - name: Check out repository code
        uses: actions/checkout@v4

      # مرحله 2: نصب و راه‌اندازی پایتون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # مرحله 3: نصب پکیج‌های مورد نیاز
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # مرحله 4: اجرای اسکریپت اصلی
      - name: Run script to generate configs
        run: python main.py

      # مرحله 5: کامیت و پوش کردن فایل
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: auto-update shadowsocks configs'
          file_pattern: 'shadowsocks.txt'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
