name: Update Proxies and Notify

on:
  # این اکشن رو هر ۶ ساعت یک‌بار اجرا می‌کنه
  schedule:
    - cron: '0 */6 * * *'
  # این خط بهت اجازه می‌ده که اکشن رو به صورت دستی هم از تب Actions اجرا کنی
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # مرحله ۱: کدها رو از ریپازیتوری دانلود می‌کنه
      - name: Checkout repository
        uses: actions/checkout@v3

      # مرحله ۲: پایتون رو نصب و آماده می‌کنه
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # مرحله ۳: نیازمندی‌های پروژه رو نصب می‌کنه
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # مرحله ۴: اسکریپت اصلی رو برای جمع‌آوری پراکسی‌ها اجرا می‌کنه
      - name: Run the update script
        run: python main.py

      # مرحله ۵: تغییرات رو کامیت و پوش می‌کنه
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          # فقط در صورتی کامیت می‌کنه که تغییری وجود داشته باشه
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "✅ Update proxy list"
            git push
            # یک متغیر برای مرحله بعد می‌سازیم تا بفهمیم تغییری بوده یا نه
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          else
            echo "No changes to commit."
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi

      # مرحله ۶: اگر تغییری وجود داشت، به تلگرام نوتیفیکیشن می‌فرسته
      - name: Send Telegram notification
        # این مرحله فقط زمانی اجرا می‌شه که در مرحله قبل تغییری ثبت شده باشه
        if: env.HAS_CHANGES == 'true'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHANNEL_ID }}" \
          -d "text=✅ لیست پراکسی‌ها آپدیت شد! 🔥%0A%0Aهمین الان می‌تونید کانفیگ‌های جدید رو از لینک زیر دریافت کنید:%0A%0Ahttps://github.com/nekovpn/omg"
