name: Update Shadowsocks Servers and Notify Telegram

on:
  schedule:
    - cron: '0 */6 * * *' # هر 6 ساعت یکبار
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script to fetch and process servers
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          # این متغیر برای ساخت لینک اشتراک در README لازم است
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # چک کردن برای وجود تغییرات در فایل‌های مهم
          if ! git diff --quiet README.md nodes.md ss_sub; then
            echo "Changes detected. Committing..."
            git add README.md nodes.md ss_sub
            git commit -m "Auto-update Shadowsocks servers [$(date -u +'%Y-%m-%d %H:%M')]"
            git push
          else
            echo "No changes to commit."
          fi
