name: Update Shadowsocks Servers and Notify Telegram

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # --- این بخش کلیدی برای حل مشکل است ---
    permissions:
      contents: write # به ورک‌فلو اجازه نوشتن (push) در ریپازیتوری را می‌دهد
    # ------------------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          if ! git diff --quiet README.md nodes.md ss_sub ss; then
            echo "Changes detected. Committing..."
            git add README.md nodes.md ss_sub ss
            git commit -m "Auto-update Shadowsocks servers [$(date -u +'%Y-%m-%d %H:%M')]"
            git push
          else
            echo "No changes to commit."
          fi
